.TH "mrcImageMaskingByImage" "EOS" "COMMANDS" "" "Mar 16, 1998"
.SH PROGRAM
mrcImageMaskingByImage \- mrcImageMaskingByImage
.syntax EOS mrcImageMaskingByImage
.SH DESCRIPTION
.SH "REQUIRED ARGUMENTS"
.IP -i 7
type: infile
.br
desc: First Input data object
.br
.IP -o 7
type: outfile
.br
desc: Resulting output data object
.br
.sp
.SH "OPTIONAL ARGUMENTS"
none
.sp
.SH EXAMPLES
.SH "SEE ALSO"
.SH RESTRICTIONS 
.SH REFERENCES 
.SH COPYRIGHT
Copyright (C) 1993 - 1996, Khoral Research, Inc.  All rights reserved.

