.TH "mrc2viff" "EOS" "COMMANDS" "" "Sep 29, 1996"
.SH PROGRAM
mrc2viff \- mrc2viff
.syntax EOS mrc2viff
.SH DESCRIPTION
.SH "REQUIRED ARGUMENTS"
.IP -i 7
type: infile
.br
desc: First Input data object
.br
.IP -o 7
type: outfile
.br
desc: Resulting output data object
.br
.sp
.SH "OPTIONAL ARGUMENTS"
none
.sp
.SH EXAMPLES
.SH "SEE ALSO"
.SH RESTRICTIONS 
.SH REFERENCES 
.SH COPYRIGHT
Copyright (C) 1993 - 1996, Khoral Research, Inc.  All rights reserved.

