#!/bin/sh
#
# ctrlShow  1.2
#
# The latest update : 01/03/96 at 21:16:00
#
#@(#) ctrl2header Function
#@(#)
#
#@(#) Usage : ctrl2header SourceFileName
#
#@(#) Attention
#@(#)
#@(#) Parameter: 
#@(#)     Essential:
#@(#)         SourceFileName
#@(#) Optional:
#@(#)
usage()
{
	echo "Usage: ctrl2header ToolName ControlFileName"
	exit
}


# Store Flags
FlagsCharacter="-"

case $# in 
	0)
		;;
	*)
		while [ `echo $1 | cut -c1` = ${FlagsCharacter} ]
		do
			case $1 in
				-h)
					usage
				;;
			esac
			parms="$ {parms} $1"
			shift 
		done
		;;
esac

case $# in
	0) # No filename 
		echo "Tool Name"
		read ToolName
		echo "Enter ControlSourceFileName"
		read ControlFileName
		;;
	2) # 
		ToolName=$1
		ControlFileName=$2
		;;
	*) #
		usage 
		;;
esac
#
currentDir=`pwd`

for file in ${ControlFileName}
do
	sed -f $EOS_HOME/sbin/sed/ctrlPre.sed ${ControlFileName} > ${ControlFileName}.tmp
	awk -f $EOS_HOME/sbin/awk/ctrlShow.awk -v ToolName=${ToolName} ${ControlFileName}.tmp 
	rm ${ControlFileName}.tmp
done
