#!/bin/sh
#
# %M% %Y% %I%
#
# The latest update : %G% at %U%
#
#%Z% ctrl2configFileRead Function
#%Z%
#
#%Z% Usage : ctrl2configFileRead SourceFileName
#
#%Z% Attention
#%Z%
#%Z% Parameter: 
#%Z%     Essential:
#%Z%         SourceFileName
#%Z% Optional:
#%Z%
usage()
{
	echo "Usage: ctrl2configFileRead ClassName ToolName ControlFileName"
	exit
}


# Store Flags
FlagsCharacter="-"

case $# in 
	0)
		;;
	*)
		while [ `echo $1 | cut -c1` = ${FlagsCharacter} ]
		do
			case $1 in
				-h)
					usage
				;;
			esac
			parms="$ {parms} $1"
			shift 
		done
		;;
esac

case $# in
	0) # No filename 
		echo "Class Name"
		read ClassName
		echo "Tool Name"
		read ToolName
		echo "Enter ControlSourceFileName"
		read ControlFileName
		;;
	1) # 
		ClassName=$1
		echo "Tool Name"
		read ToolName
		echo "Enter ControlSourceFileName"
		read ControlFileName
		;;
	2) # 
		ClassName=$1
		ToolName=$2
		echo "Enter ControlSourceFileName"
		read ControlFileName
		;;
	3) # 
		ClassName=$1
		ToolName=$2
		ControlFileName=$3
		;;
	*) #
		usage 
		;;
esac
#
currentDir=`pwd`

for file in ${ControlFileName}
do
	sed -f $EOS_HOME/sbin/sed/ctrlPre.sed ${ControlFileName} > ${ControlFileName}.tmp
	awk -f $EOS_HOME/sbin/awk/ctrl2Function.awk -f $EOS_HOME/sbin/awk/ctrl2configFileRead.awk -v ClassName=${ClassName} -v ToolName=${ToolName} ${ControlFileName}.tmp 
	awk -f $EOS_HOME/sbin/awk/ctrl2Function.awk -f $EOS_HOME/sbin/awk/ctrl2configFileUsage.awk -v ClassName=${ClassName} -v ToolName=${ToolName} ${ControlFileName}.tmp 
	rm ${ControlFileName}.tmp
done
