#!/bin/sh
#
# objectHeadAdd  1.1
#
# The latest update : 04/30/96 at 21:52:10
#
#@(#) toolHeadAdd Function
#@(#)
#
#@(#) Usage : toolHeadAdd SourceFileName
#
#@(#) Attention
#@(#)
#@(#) Parameter: 
#@(#)     Essential:
#@(#)         SourceFileName
#@(#)     Optional:
#@(#)

usage()
{
	echo "Usage: toolHeadAdd SourceFileName"
}

NameRead()
{
	ans="N"
	while [ $ans != "Y" -a $ans != "y" ]
	do
		echo $1
		read Name
		echo "$Name is good ?"
		read ans
	done
}
# Store Flags
FlagsCharacter="-"

case $# in 
	0)
		;;
	*)
		while [ `echo $1 | cut -c1` = ${FlagsCharacter} ]
		do
			if [ `echo $1 | cut -c2` = "h" ] 
			then
				usage
			else
				parms="${parms} $1"
				shift 
			fi
		done
		;;
esac

case $# in
	0) # No filename 
		echo "Enter SourceFileName"
		read filename
		;;
	1) # 
		filename=$1
		;;
	*) #
		filename="$*"
		;;
esac
#
currentDir=`pwd`

for file in ${filename}
do
	FullName=${currentDir}/${file}	
	Name=`basename ${FullName} .c`
	Dir=`dirname ${FullName}`
	
	mv ${file} ${file}.org
	sed -e s/Obj/${Name}/g ${EOS_HOME}/sbin/objectHead.Template >  ${file}
	echo "/* \$Log\$ */"                                        >> ${file}
	cat ${file}.org                                             >> ${file}
done
