#!/bin/sh
#
# protoObjectMethodCreate  1.5
#
# The latest update : 05/28/96 at 08:47:32
#
#@(#) protoObjectMethodCreate Function
#@(#)
#
#@(#) Usage : protoObjectMethodCreate SourceFileName
#
#@(#) Attention
#@(#)
#@(#) Parameter: 
#@(#)     Essential:
#@(#)         SourceFileName
#@(#)     Optional:
#@(#)

usage()
{
	echo "Usage: protoObjectHeaderCreate HeaderFileName"
}

NameRead()
{
	ans="N"
	while [ $ans != "Y" -a $ans != "y" ]
	do
		echo $1
		read Name
		echo "$Name is good ?"
		read ans
	done
}
# Store Flags
FlagsCharacter="-"

case $# in 
	0)
		;;
	*)
		while [ `echo $1 | cut -c1` = ${FlagsCharacter} ]
		do
			if [ `echo $1 | cut -c2` = "h" ] 
			then
				usage
			else
				parms="${parms} $1"
				shift 
			fi
		done
		;;
esac

case $# in
	0) # No filename 
		echo "Enter Header FileName"
		read filename
		;;
	1) # 
		filename=$1
		;;
	*) #
		filename=$*
		;;
esac
#
currentDir=`pwd`

for file in ${filename}
do
	FullName=${currentDir}/${file}	
	Name=`basename ${FullName} .c`
	Dir=`dirname ${FullName}`
	if [ -f ${FullName} ]
	then
		ans = "N"
		echo "The file, ${file} exists. May I overwrite it ?"
		read ans
		if [ $ans != "y" -a $ans != "Y" ]
		then 
			break
		fi
		mv ${FullName} ${FullName}.org
	fi
	echo "Creationg a new method, ${file} !!"
	touch ${FullName}
	objectHeadAdd  ${FullName}
	cat ${EOS_HOME}/sbin/protoObjectHeaderCreate.Template | sed  -e s/\$\{Name\}/${Name}/g >> ${FullName}
done

make depend
