#!/bin/sh
# sccsUnedit  1.1
#
# The latest update : at 15:58:01
#
#@(#) A new SCCS file is created if no SCCS. If one have SCCS, delta commands.
#@(#) 
#
#@(#) Usage : sccsUnedit SourceFileName
#@(#)
#@(#) Attention
#@(#)
#@(#) Parameter: 
#@(#)     Essential:
#@(#)         SourceFileName
#@(#)     Optional:
#@(#)

# Store Flags
FlagsCharacter="-"

while [ `echo $1 | cut -c1` = "-" ]
do
	parms="$ {parms} $1"
	shift 
done

case $# in
	0) # No filename 
		echo "Enter SourceFileName"
		read filename
		;;
	1) # 
		filename=$1
		;;
	*) #
		filename="$*"
		;;
esac
#
EosSCCSHome=$EOS_HOME/sccs
currentDir=`pwd`

for file in ${filename}
do
	FullName=${currentDir}/${file}	
	Name=`basename ${FullName}`
	Dir=`dirname ${FullName}`
#	echo Full=${FullName} Name=${Name} EosHome=$EOS_HOME

	currentSCCSDir=`echo $Dir | awk '{sub(/\/[a-zA-Z0-9\/]*\/Eos\//, ""); print $0}'` 
	sccsDir=${EosSCCSHome}/${currentSCCSDir}
#	echo sccsDir=${sccsDir} currentSCCSDir=${currentSCCSDir}
#	exit

	echo ">>>> ${Name}"

	if [ -x $file ]
	then 
		Executable="+x"
	else
		Executable="-x"
	fi

	if [ -f ${sccsDir}/s.${Name} ] 
	then
		unget ${sccsDir}/s.${Name} 
	else 
		echo "You have no sccs file (${Name})"
	fi
	if [ -f ${file} ]
	then
		if [ -f ${sccsDir}/s.${Name} ]
		then
			rm $file
		fi
	fi

	cd ${Dir}
	get   ${sccsDir}/s.${Name}
	chgrp Eos ${Name}
	chmod 444 ${Name}
	chmod ${Executable} ${Name}
done
