#!/bin/sh
# 
# sccsReport  1.1
#
# The latest update : 04/25/96 at 10:48:08
#
#@(#) A new SCCS file is reported. 
#@(#) 
#
#@(#) Usage : sccsReport [SourceFileName]
#
#@(#) Attention
#@(#)
#@(#) Parameter: 
#@(#)    Essential:
#@(#)       SourceFileName
#@(#)    Optional:
#@(#) 

# Store Flags
FlagsCharacter="-"

while [ `echo $1 | cut -c1` = "-" ]
do
	parms="$ {parms} $1"
	shift 
done

case $# in
	0) # No filename 
		echo "Enter SourceFileName"
		read filename
		;;
	1) # 
		filename=$1
		;;
	*) #
		filename="$*"
		;;
esac
#
EosSCCSHome=$EOS_HOME/sccs
currentDir=`pwd`

for file in ${filename}
do
	FullName=${currentDir}/${file}	
	Name=`basename ${FullName}`
	Dir=`dirname ${FullName}`
	echo Full=${FullName} Name=${Name} EosHome=$EOS_HOME

	currentSCCSDir=`echo $Dir | awk '{gsub(/\/[a-zA-Z0-9\/]*\/Eos\//, ""); print $0}'` 
	sccsDir=${EosSCCSHome}/${currentSCCSDir}
	echo sccsDir=${sccsDir} currentSCCSDir=${currentSCCSDir}

	if [ -x $file ]
	then 
		Executable="+x"
	else
		Executable="-x"
	fi

	cd ${Dir}
	if [ -f ${sccsDir}/s.${Name} ] 
	then
		prs ${sccsDir}/s.${Name}
	else
		echo "No sccs files are found."
	fi
	chmod ${Executable} ${Name}
done

