# Makefile.config for 2D Clustering 

# Cluster Name
CLUSTER=all

# Pad Parameter
#  Width(Nx) before shrinking 
PADWIDTH=32
#  Height(Ny) before shrinking 
PADHEIGHT=32
#  Shrink for Speed Up in clustering
SHRINK=1
#  Pad Mode 
PADMODE=13
#  LOWPASS
LowPassMode=4 
LowPassResolution=0.1

# Clustering
ClusterCorrelationMode=19
#
ClusterRotationRangeMin=0
ClusterRotationRangeMax=360
ClusterRotationRangePartitionNumber=72
ClusterRotationIterationNumber=2
ClusterRotationCorrelationMode=0
#
ClusterMode=2


# ClusterShow
TreeRootPositionX=0
TreeRootPositionY=400
TreeScaleX=15
TreeScaleY=150
TreeOffset=1e1
